### ISSUE TITLE
i added lavacord dev vers and this happened

### ISSUE THREAD

**Issue by TheUsual10k** [Allvaa/lavalink-musicbot#102]
![image](https://user-images.githubusercontent.com/82567115/119615847-52f24100-be19-11eb-82db-89e1ed5eeddd.png)

**Comment by Allvaa** [comment]
if you install the package from github, you can't. on the repo itself doesn't include compiled files (dist folder)

**Comment by TheUsual10k** [comment]
what should i do then?

**Comment by Allvaa** [comment]
compile yourself

**Comment by TheUsual10k** [comment]
Fixed
