### ISSUE TITLE
Buttons / slash commands

### ISSUE THREAD

**Issue by rajamoulimallareddy** [Allvaa/lavalink-musicbot#103]
implementation of Buttons in Queue

**Comment by yofukashino** [comment]
wait what buttons can you explain please

**Comment by yofukashino** [comment]
IG you should wait for Discord.JS 13

**Comment by rajamoulimallareddy** [comment]
> IG you should wait for Discord.JS 13

yep

**Comment by rajamoulimallareddy** [comment]
@Allvaa how to load Spotify artists.

**Comment by yofukashino** [comment]
I do that with other packages

**Comment by rajamoulimallareddy** [comment]
hey @Allvaa for queue make a component collector instead of emoji collector

**Comment by Allvaa** [comment]
> hey @Allvaa for queue make a component collector instead of emoji collector

yeah, I would do that
