### ISSUE TITLE
When I host this on a VPS it receives but doesn't play Spotify playlists

### ISSUE THREAD

**Issue by dslvd** [Allvaa/lavalink-musicbot#123]

**Comment by rajamoulimallareddy** [comment]
> _No description provided._

try keeping autoResolve: true in (MusicClient.js where u defined lavasfy or Spotify manager) @mercenaryexc

**Comment by dslvd** [comment]
> > _No description provided._
> 
> try keeping autoResolve: true in (MusicClient.js where u defined lavasfy or Spotify manager) @mercenaryexc

Auto resolve?

**Comment by rajamoulimallareddy** [comment]
> > > _No description provided._
> > 
> > 
> > try keeping autoResolve: true in (MusicClient.js where u defined lavasfy or Spotify manager) @mercenaryexc
> 
> Auto resolve?

autoResolve: true
 yep

**Comment by yofukashino** [comment]
bruh close the issue atleast
