### ISSUE TITLE
Fix SoundCloud {Invalid status code for soundcloud stream: 401}

### ISSUE THREAD

**Issue by devPhytols** [Allvaa/lavalink-musicbot#125]
error: Invalid status code for soundcloud stream: 401

**Comment by Allvaa** [comment]
update your lavalink to the latest dev version from the CI

**Comment by rajamoulimallareddy** [comment]
> error: Invalid status code for soundcloud stream: 401

https://ci.fredboat.com/repository/download/Lavalink_Build/8871:id/Lavalink.jar?guest=1

use this latest lava link

**Comment by devPhytols** [comment]
solved, thanks <3
