### ISSUE TITLE
How to set default volume?

### ISSUE THREAD

**Issue by thetechguy-cpu** [Allvaa/lavalink-musicbot#128]
Hi there.
Is there a way to set a default volume for every guild in the config?
Thanks.

**Comment by Allvaa** [comment]
unfortunately there is no

**Comment by thetechguy-cpu** [comment]
Hi there.
How about a volume caching system? So that when I do /volume [number] it caches it for the guild?

**Comment by Allvaa** [comment]
yeah it is cached there 
https://github.com/Allvaa/lavalink-musicbot/blob/04c6ed72728f95fc28d7fd6a2b15901b1f7cb6b7/src/structures/MusicHandler.js#L8
https://github.com/Allvaa/lavalink-musicbot/blob/04c6ed72728f95fc28d7fd6a2b15901b1f7cb6b7/src/structures/MusicHandler.js#L121-L127

anyway if you want to set default volume, just pass the second parameter of the function there
https://github.com/Allvaa/lavalink-musicbot/blob/04c6ed72728f95fc28d7fd6a2b15901b1f7cb6b7/src/structures/MusicHandler.js#L91

**Comment by thetechguy-cpu** [comment]
> anyway if you want to set default volume, just pass the second parameter of the function there
> https://github.com/Allvaa/lavalink-musicbot/blob/04c6ed72728f95fc28d7fd6a2b15901b1f7cb6b7/src/structures/MusicHandler.js#L91

Hi there.

What would I need to change in that line to set the default volume?
Thanks.

**Comment by Allvaa** [comment]
> > anyway if you want to set default volume, just pass the second parameter of the function there
> > https://github.com/Allvaa/lavalink-musicbot/blob/04c6ed72728f95fc28d7fd6a2b15901b1f7cb6b7/src/structures/MusicHandler.js#L91
> 
> Hi there.
> 
> What would I need to change in that line to set the default volume?
> Thanks.

as I said, you need to pass the second parameter, like `{ volume: value }`
