### ISSUE TITLE
Error when starting bot.

### ISSUE THREAD

**Issue by CutieBray** [Allvaa/lavalink-musicbot#142]
Encountered an error in node main. Error: write EPROTO 7012:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16) {
  errno: -4046,
  code: 'EPROTO',
  syscall: 'write'
}
Node main closed. Code: 1006. Reason: .
Node main disconnected.

I've configured everything correctly, lavalink, etc. Any idea?

**Comment by Allvaa** [comment]
which branch are you running?

**Comment by Allvaa** [comment]
i think i see your problem, try to set LAVA_SECURE to false

**Comment by CutieBray** [comment]
> i think i see your problem, try to set LAVA_SECURE to false

I'm running djs13, when setting LAVA_SECURE to false, it connects then show's - 
Node main is now ready.
Node main closed. Code: 1011. Reason: .

**Comment by Allvaa** [comment]
use this latest dev build https://ci.fredboat.com/repository/download/Lavalink_Build/8871:id/Lavalink.jar since the lavalink client used by the bot doesn't support master build anymore

**Comment by CutieBray** [comment]
> use this latest dev build https://ci.fredboat.com/repository/download/Lavalink_Build/8871:id/Lavalink.jar since the lavalink client used by the bot doesn't support master build anymore

Works now! Thanks :D
