### ISSUE TITLE
[djs13] bot keeps disconnecting and reconnecting to Lavalink server.

### ISSUE THREAD

**Issue by thetechguy-cpu** [Allvaa/lavalink-musicbot#149]
Hi.
This affects the djs13 branch. When ever I do npm start, I get the following from the console.

```
 Node main is now ready.                                                         
 Node main closed. Code: 1011. Reason: .                                         
 Node main is now ready.                                                         
 Node main closed. Code: 1011. Reason: .                                         
 Node main is now ready.                                                         
 Node main closed. Code: 1011. Reason: .                                         
 ```
My lavalink server is stable and this does not happen to the master branch of the bot. How can I fix this?

**Comment by thetechguy-cpu** [comment]
Hi.
Im closing this issue as I was able to resolve it by using the latest dev build of Lavalink. It turns out i was using the latest stable version not the latest dev version.

**Comment by Allvaa** [comment]
yeah its already written in the readme
