### ISSUE TITLE
[DJS13]Setting default volume?

### ISSUE THREAD

**Issue by thetechguy-cpu** [Allvaa/lavalink-musicbot#157]
Hi.

I'm trying to set a default volume for the bot when joining a vc. Here's what I've tried so far:

https://github.com/Allvaa/lavalink-musicbot/blob/0e47d9b086e88021c4b813f2e572de9f1529c581/src/structures/MusicHandler.js#L114

I changed it to:
`        this.player?.playTrack(this.queue[0].track, {volume: 15});`

However, it stil plays the music at 100% volume. I've also tried changing it to:

`        this.player?.playTrack(this.queue[0].track, {setVolume: 15});`

However it still won't work. What am I doing wrong here?

**Comment by yofukashino** [comment]
Why don't you use the already defined function to set volume which should be this.setVolume(volume) add this after playing the track it will be default volume IG

**Comment by thetechguy-cpu** [comment]
> Why don't you use the already defined function to set volume which should be this.setVolume(volume) add this after playing the track it will be default volume IG

Hi.

When I change it using that function:

`this.player?.playTrack(this.queue[0].track, {this.setVolume(15)});`

I get the following error:

`SyntaxError: Unexpected token '.'`

How can I fix this?

**Comment by yofukashino** [comment]
if use `this.player?.playTrack(this.queue[0].track);
this.setVolume(15);`

**Comment by thetechguy-cpu** [comment]
> if use `this.player?.playTrack(this.queue[0].track); this.setVolume(15);`

Thank you. That seems to work.
