### ISSUE TITLE
Need Some Features!

### ISSUE THREAD

**Issue by yofukashino** [Allvaa/lavalink-musicbot#47]
Can You Add Some Features Like:
1.Skipto
2.Move
3.The Bot Doesn't Leave VC immediately but Sends a Message about it.
Else Your Bot is Awesome after the Tweaks I made to My Personal Version! :D
GG/

**Comment by Allvaa** [comment]
added skipto (merged in skip command). by the way im not sure what you mean with "Move" can you tell it specifically?

**Comment by yofukashino** [comment]
> added skip to (merged in skip command). by the way, I'm not sure what you mean with "Move" can you tell it specifically?

By Move, I mean the ability to move a song to any no in the queue. and also a previous command.

**Comment by Allvaa** [comment]
added move and previous. 

> The Bot Doesn't Leave VC immediately but Sends a Message about it.

i thought you can do this by yourself using setTimeout function. it's already sends message, just need to add timeout for the bot to leave vc

**Comment by Allvaa** [comment]
anyway, thanks for your suggestion :) please let me know if there is a bug.

i'll close this rn
