### ISSUE TITLE
Some features

### ISSUE THREAD

**Issue by gonzyui** [Allvaa/lavalink-musicbot#49]
Hey, I think that will be good to add somethings, like when only bot is on VC, bot leave VC after 15 seconds.
And why not some playlists managing by database ? @Allvaa

**Comment by tolisdev** [comment]
Personally, a musicbot does not need a database. It will make it more complex. Other than that, it is easy to make it in your own version. I personally added databases for playlist and error logging, and it works fantastic!

**Comment by gonzyui** [comment]
i don't use this code for my own bot, i purpose this cuz i think its cool

**Comment by yofukashino** [comment]
> i don't use this code for my own bot, i purpose this cuz i think its cool

Omae wa mou shinderu

**Comment by Allvaa** [comment]
i don't think to add playlists managing with db, sorry
