### ISSUE TITLE
ADD premium cmds. 

### ISSUE THREAD

**Issue by rajamoulimallareddy** [Allvaa/lavalink-musicbot#51]
why don't u add filers like bass-boost, nightcore,8D, speed, 24/7, pitch, vaporwave, saved queues? commands. and connect it mongo db server if possible. @AlvvxL  @Allvaa @mina9999

**Comment by tolisdev** [comment]
Why would you need Mongo? But other than that, I think these commands have to be added!
 Also, a good idea is to make now playing command show more info...

**Comment by kotx** [comment]
What do you mean by "premium"?

**Comment by rajamoulimallareddy** [comment]
> What do you mean by "premium"?

i mean bass-boost, nightcore,8D, speed, 24/7, pitch, vaporwave, saved queues, custom prefix.
@kotx

**Comment by yofukashino** [comment]
I have made custom prefix command. If you want it I may share the code!

**Comment by KasaiKonoru** [comment]
> I have made custom prefix command. If you want it I may share the code!

yes pls ^^

**Comment by rajamoulimallareddy** [comment]
> I have made custom prefix command. If you want it I may share the code!

@LoneWeebGod please share the code for the custom prefix.

**Comment by yofukashino** [comment]
> > I have made custom prefix command. If you want it I may share the code!
> 
> @LoneWeebGod please share the code for the custom prefix.

as per you asked The Prefix Command need a change in three files:
1.MusicClient.js 
Remove this From the File `this.prefix = process.env.PREFIX;`
2. Message.js
Let the Code be Like of this file : [Message.js](https://cdn.discordapp.com/attachments/775376498769002498/817950533620203535/message.js)
3.Last but Not Least Cmd It Self 
[Prefix.js](https://cdn.discordapp.com/attachments/775376498769002498/817949483517345852/setprefix.js)

Note: add a File name `prefixes.json`  with content `{ }` in the Root Directory of Bot
Prefixes.json For Example: [Prefixes.json](url)
