### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by yofukashino** [Allvaa/lavalink-musicbot#53]
Add a Variation to Loop to choose weather to Loop Single or queue

**Comment by NiklasGamerHD** [comment]
Good idea!

**Comment by yofukashino** [comment]
ok I Made the Code My Self GG (￣_,￣ )

**Comment by NiklasGamerHD** [comment]
Can you send the code pls xD?

**Comment by yofukashino** [comment]
> Can you send the code pls xD?

The Loop Command is Now [Loop.js](https://cdn.discordapp.com/attachments/604315049187606538/819597532417359912/loop.js)


You Also Need to make some changes in the Music handler as in this File [MusicHandeler.js](https://cdn.discordapp.com/attachments/604315049187606538/819599064022646824/MusicHandler.js)


You Can Loop a Single Song or The Whole Queue or Just turn it off. and If no Args Provided then it will Just cycle (Single>Queue>Off) Just Very User Friendly φ(*￣0￣)

**Comment by yofukashino** [comment]
@Allvaa Just add this code to the bot and improve it if any are there!
