### ISSUE TITLE
New Feature: Now Playing Progress bar

### ISSUE THREAD

**Issue by KasaiKonoru** [Allvaa/lavalink-musicbot#54]
Hello. The bot is very good, but the only think what I miss is a now playing progress bar.
At what minute the music is playing / how long it will continue to play

**Comment by yofukashino** [comment]
Sir I have a code for that. If you want I may share it to you!

**Comment by rajamoulimallareddy** [comment]
> Sir I have a code for that. If you want I may share it to you!

@LoneWeebGod what code and can u share it ?

**Comment by LoneWeebGod** [comment]
> > Sir I have a code for that. If you want I may share it to you!
> 
> @LoneWeebGod what code and can u share it ?

`const util = require("../util");
const { porgressBar } = require("music-progress-bar");
const prettyMilliseconds = require('pretty-ms');

module.exports = {
    name: "nowplaying",
    aliases: ["np", "nowplay"],
    exec: (msg, messgae ,args, bot, client) => {
        const { music } = msg.guild;
		msg.delete({ timeout: 000 /*time unitl delete in milliseconds*/});
		 if (!music.player || !music.player.playing) return msg.channel.send(util.embed().setDescription("❌ | Currently not playing anything.")		
		.setFooter(msg.author.username,  msg.author.displayAvatarURL({ dynamic: true }))
		.setTimestamp()).then(msg => msg.delete({ timeout: 10000 }));
		const yid = (music.current.info.identifier);
		const img = ("https://img.youtube.com/vi/");
		const las = ("/maxresdefault.jpg");
		const rem = (music.current.info.length - music.player.state.position /1)
        const rom = prettyMilliseconds(rem, { colonNotation: true, secondsDecimalDigits: 0 });
	
		let nowPlaying = util.embed()
		.setTitle(`**${music.current.info.title}**.`)
		.setURL(`${music.current.info.uri}`)
		.setImage(`${img}${yid}${las}`)
		.setAuthor(`🎶 | Now playing `, msg.client.user.displayAvatarURL())
				
		.setTimestamp()
		;		
		if (music.current.info.isStream ) {
		nowPlaying.addField("\u200b", ":satellite:**The Video Is Live ◉**")
		.setFooter(msg.author.username, msg.author.displayAvatarURL({ dynamic: true }))
		}
		else if 
		(music.player.state.position > 0) {
		nowPlaying.addField("\u200b", porgressBar({currentPositon:music.player.state.position /1,endPositon:music.current.info.length,width:28,barStyle:"=",currentStyle:"🔘"}, {format:" [ <bar> ] <precent> <%>"}))
		.setFooter(`Time Remaining: ${rom} Mins`, msg.author.displayAvatarURL({ dynamic: true }))
		}
		else {
			nowPlaying.setFooter(msg.author.username, msg.author.displayAvatarURL({ dynamic: true }))
			}
		return msg.channel.send(nowPlaying).then(msg => msg.delete({ timeout: 60000 }));
		
}};
`

**Comment by yofukashino** [comment]
> > Sir I have a code for that. If you want I may share it to you!
> 
> @LoneWeebGod what code and can u share it ?


[NowPlaying.js](https://cdn.discordapp.com/attachments/604315049187606538/813797104962109506/nowplaying.js)

**Comment by KasaiKonoru** [comment]
> 
> 
> > > Sir I have a code for that. If you want I may share it to you!
> > 
> > 
> > @LoneWeebGod what code and can u share it ?
> 
> [NowPlaying.js](https://cdn.discordapp.com/attachments/604315049187606538/813797104962109506/nowplaying.js)

but cannot find module music-progress-bar
And hoe can i let the bot writes the youtube title or spotify link in thr description

**Comment by yofukashino** [comment]
> > [](https://cdn.discordapp.com/attachments/604315049187606538/813797104962109506/nowplaying.js)
> 
> but cannot find module music-progress-bar

use `npm i music-progress-bar`
to resolve the "cannot find module music-progress-bar" issue and Try The Command The Title is already in the description and if you click on it then the link is embedded into the title itself so no worries. have fun

**Comment by KasaiKonoru** [comment]
> > > 
> > 
> > 
> > but cannot find module music-progress-bar
> 
> use `npm i music-progress-bar`
> to resolve the "cannot find module music-progress-bar" issue and Try The Command The Title is already in the description and if you click on it then the link is embedded into the title itself so no worries. have fun

**How I can add the duration of the song in Min. in the automatic now playing message?**

**Comment by yofukashino** [comment]
> > > > 
> > > 
> > > 
> > > but cannot find module music-progress-bar
> > 
> > 
> > use `npm i music-progress-bar`
> > to resolve the "cannot find module music-progress-bar" issue and Try The Command The Title is already in the description and if you click on it then the link is embedded into the title itself so no worries. have fun
> 
> **How I can add the duration of the song in Min. in the automatic now playing message?**

can you explain what you want in detail

**Comment by KasaiKonoru** [comment]
> > > > > 
> > > > 
> > > > 
> > > > but cannot find module music-progress-bar
> > > 
> > > 
> > > use `npm i music-progress-bar`
> > > to resolve the "cannot find module music-progress-bar" issue and Try The Command The Title is already in the description and if you click on it then the link is embedded into the title itself so no worries. have fun
> > 
> > 
> > **How I can add the duration of the song in Min. in the automatic now playing message?**
> 
> can you explain what you want in detail

Now: If a new song is playing there will send a message with title. But i want in the embed the duration. But if i use duration It shows the milliseconds

**Comment by rajamoulimallareddy** [comment]
> > > > > 
> > > > 
> > > > 
> > > > but cannot find module music-progress-bar
> > > 
> > > 
> > > use `npm i music-progress-bar`
> > > to resolve the "cannot find module music-progress-bar" issue and Try The Command The Title is already in the description and if you click on it then the link is embedded into the title itself so no worries. have fun
> > 
> > 
> > **How I can add the duration of the song in Min. in the automatic now playing message?**
> 
> can you explain what you want in detail

can you provide your discord id or discord server link.

**Comment by yofukashino** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > but cannot find module music-progress-bar
> > > > 
> > > > 
> > > > use `npm i music-progress-bar`
> > > > to resolve the "cannot find module music-progress-bar" issue and Try The Command The Title is already in the description and if you click on it then the link is embedded into the title itself so no worries. have fun
> > > 
> > > 
> > > **How I can add the duration of the song in Min. in the automatic now playing message?**
> > 
> > 
> > can you explain what you want in detail
> 
> Now: If a new song is playing there will send a message with title. But i want in the embed the duration. But if i use duration It shows the milliseconds

Use this Node Module:  [Preety MS](https://www.npmjs.com/package/pretty-ms)

**Comment by LoneWeebGod** [comment]
Should Probably Close this Issue Now~!

**Comment by yofukashino** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > but cannot find module music-progress-bar
> > > > 
> > > > 
> > > > use `npm i music-progress-bar`
> > > > to resolve the "cannot find module music-progress-bar" issue and Try The Command The Title is already in the description and if you click on it then the link is embedded into the title itself so no worries. have fun
> > > 
> > > 
> > > **How I can add the duration of the song in Min. in the automatic now playing message?**
> > 
> > 
> > can you explain what you want in detail
> 
> can you provide your discord id or discord server link.

`ℓσɳεωεεɓ αɦℓαωαƭ#7464` this is my Discord ID

https://discord.gg/nxB3UVy2 And This is The server I am developing the bot for. I am Mostly active here only!

**Comment by yofukashino** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > but cannot find module music-progress-bar
> > > > 
> > > > 
> > > > use `npm i music-progress-bar`
> > > > to resolve the "cannot find module music-progress-bar" issue and Try The Command The Title is already in the description and if you click on it then the link is embedded into the title itself so no worries. have fun
> > > 
> > > 
> > > **How I can add the duration of the song in Min. in the automatic now playing message?**
> > 
> > 
> > can you explain what you want in detail
> 
> Now: If a new song is playing there will send a message with title. But i want in the embed the duration. But if i use duration It shows the milliseconds

Use `util.millisToDuration(<song length in ms>)`
