### ISSUE TITLE
Multiple Nodes

### ISSUE THREAD

**Issue by yofukashino** [Allvaa/lavalink-musicbot#62]
I have Like Two Lavalink servers! So can you make the code like if one fails so it automatically shifts to the other one?
and we just have to put the info of both in the .env file nothing else. Is it Possible?

**Comment by Allvaa** [comment]
we can use this https://lavacord.github.io/Lavacord/classes/manager.html#idealnodes, also storing nodes in a json file rather than .env is a good option for that i think

**Comment by yofukashino** [comment]
please make it I was trying but couldn't find a solution to my problems.
