### ISSUE TITLE
Just Why Senpai

### ISSUE THREAD

**Issue by yofukashino** [Allvaa/lavalink-musicbot#64]
The Code working Till Yestartday But Stopped working today 
the code was `constructor(guild) {
		this.guild = guild;
this.queue.loop = null;
	 if (this.current) {this.current.loop = null;}
        this.volume = 100;
        this.previous = null;
        this.current = null;
        this.queue = [];
		        /** @type {import("discord.js").TextChannel|null} */
        this.textChannel = null;
    }`

in ./src/structures/MusicHandler.js

The Solution wil be `constructor(guild) {
		this.guild = guild;
        this.volume = 100;
        this.previous = null;
        this.current = null;
        this.queue = [];
		this.queue.loop = null;
	 if (this.current) {this.current.loop = null;}
        /** @type {import("discord.js").TextChannel|null} */
        this.textChannel = null;
    }`

Just move the Loop things to After `this.queue = [];`

**Comment by Allvaa** [comment]
fixed in the latest commit
