### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hadiabbasjafry** [Allvaa/lavalink-musicbot#68]
![image](https://user-images.githubusercontent.com/73752101/113324000-082fdd80-9330-11eb-849d-2fa3ce924b63.png)
any idea why this happened?

**Comment by KagChi** [comment]
maybe the node get rate limited.

**Comment by Allvaa** [comment]
try to use the latest lavalink

**Comment by hadiabbasjafry** [comment]
Fixed the Issue
