### ISSUE TITLE
Lyrics command

### ISSUE THREAD

**Issue by joeyk710** [Allvaa/lavalink-musicbot#74]
The current lyrics command seems to only work if you search lyrics for a song. Is it possible to also make it find lyrics for the song playing and produce a message if lyrics are not found for the song playing? Most music bots with lyric commands use both features.

**Comment by Abdul1810** [comment]
requires ksoft api

**Comment by joeyk710** [comment]
If that was added, would it change the whole base of the code or is it just simple downloading from npm?

**Comment by rajamoulimallareddy** [comment]
@joeyk710 just a simple coding

**Comment by Allvaa** [comment]
i supposed to do it a few months ago, now it's added on the commit. the lyrics may couldn't be found or even mismatch anyway
