### ISSUE TITLE
Node Problem

### ISSUE THREAD

**Issue by StormzsDev** [Allvaa/lavalink-musicbot#76]
I kept getting this error: v

Logged in as BeatBoost#7651
Node main got an error: connect ECONNREFUSED  localhost:3000

**Comment by KagChi** [comment]
make sure you alr run the lavalink in localhost

**Comment by StormzsDev** [comment]
> make sure you alr run the lavalink in localhost

how?

**Comment by KagChi** [comment]
[See Lavalink configuration here](https://github.com/freyacodes/Lavalink#server-configuration) also lavalink need java 13.

**Comment by Allvaa** [comment]
the server probably doesn't run on the address

**Comment by Allvaa** [comment]
due to inactivity
