### ISSUE TITLE
I've cloned the code but It leaves the VC 

### ISSUE THREAD

**Issue by RobbieCutler** [Allvaa/lavalink-musicbot#77]
I'll ask the bot to play something like Toosie Slide it will join then leave instantly

**Comment by RobbieCutler** [comment]
and it happens on other songs too

**Comment by Allvaa** [comment]
any logs when the bot leave?

**Comment by TheUsual10k** [comment]
send the console error when you play anything , the most probable reason could be Lavalink Node Problem , Most probably your lavalink got rate limited or banned.

**Comment by yofukashino** [comment]
try Hosting Lavalink on your Machine instead of a server and then tell if you get the error
