### ISSUE TITLE
Reaction Commands

### ISSUE THREAD

**Issue by yofukashino** [Allvaa/lavalink-musicbot#81]
I am not asking for Reaction Commands Like Hydra just wanted to tell you that I made them. If you want them then just tell me I may add a Pull request and I also added Message Purging.

**Comment by TheUsual10k** [comment]
Gib code boi

**Comment by yofukashino** [comment]
> Gib code boi

really there is a small issue but it's pretty small.

**Comment by Allvaa** [comment]
well, nah. i just wanna keep this as simple as possible

**Comment by yofukashino** [comment]
ok

**Comment by TheUsual10k** [comment]
Send me the code though xd.
